from __future__ import annotations

import json
from pathlib import Path

import yaml

from seeds.curation import apply_data_corrections, tag_movement_patterns

ROOT = Path(__file__).resolve().parent
DATASET = ROOT / "exercises.json"
OUTPUT = ROOT / "movement_patterns.yaml"


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def main() -> None:
    data = json.loads(DATASET.read_text(encoding="utf-8"))
    corrections_path = ROOT / "data_corrections.yaml"
    if corrections_path.exists():
        data = apply_data_corrections(data, yaml.safe_load(corrections_path.read_text(encoding="utf-8")) or {})
    lines = [
        "# Generated by seeds/build_movement_patterns.py.",
        "# Heuristic-first tags; safety-relevant tags should be manually reviewed.",
        "",
    ]
    reviewed_count = 0
    for exercise in sorted(data, key=lambda item: item["id"]):
        tags = tag_movement_patterns(exercise)
        if tags:
            reviewed_count += 1
        lines.append(f"{yaml_quote(exercise['id'])}:")
        if tags:
            for tag in tags:
                lines.append(f"  - {tag}")
        else:
            lines.append("  []")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT} with {reviewed_count} tagged exercises")


if __name__ == "__main__":
    main()
